- name: Create new Docker container
  hosts: all
  tasks:
    - name: Set container name variable
      set_fact:
        container_name: "git-ansible-docker"

    - name: Run Docker container
      become: yes
      command: "docker run -itd --name {{ container_name }} -p 80:80 anushac1999/git-ansible-docker"
